---
conditions: v1

stages:
  - name: test

sudo: required
dist: xenial
language: python

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/

cache: pip
jobs:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=linting TOXCFG=tox.ini
      stage: test

    - python: 3.9
      env: TOXENV=py39 TOXCFG=tox.ini
      stage: test

    - python: 3.8
      env: TOXENV=py38 TOXCFG=tox.ini
      stage: test

    - python: 3.7
      env: TOXENV=py37 TOXCFG=tox.ini
      stage: test

    - python: 3.6
      env: TOXENV=py36 TOXCFG=tox.ini
      stage: test

install:
  - pip install tox-travis setuptools --upgrade

# command to run tests
script:
  - tox -c ${TOXCFG}
